Benches refactor
clockworklabs/SpacetimeDB pull request #131
Opened 2023-08-02 15:26 UTC by mamcx

# Description of Changes

Moving out from the bench timings the creation of dbs because is expensive -in special for spacetime that creates folders vs sqlite just a file- and generates noise.

# API

 - [ ] This is a breaking change to the module API
 - [ ] This is a breaking change to the ClientAPI
 - [ ] This is a breaking change to the SDK API

*If the API is breaking, please state below what will break*

2023-08-02 20:49 UTC, cloutiertyler requested changes
Requesting changes so this doesn't actually merge. Need to look at the batch api.

2023-08-21 20:57 UTC, kulakowski commented
> Requesting changes so this doesn't actually merge. Need to look at the batch api.

Do you want me to take a look at this?

2023-09-09 08:38 UTC, cloutiertyler commented
> > Requesting changes so this doesn't actually merge. Need to look at the batch api.
> 
> Do you want me to take a look at this?

Yes please @kulakowski

2023-09-11 20:57 UTC, mamcx commented on crates/core/src/db/datastore/traits.rs
> +            table_name: format!("t_{:x}", calculate_hash(&value)),
This line will be unnecessary in the [schema rework PR](https://github.com/clockworklabs/SpacetimeDB/pull/243).

2023-09-12 15:00 UTC, mamcx commented on crates/core/src/db/datastore/traits.rs
> +            table_name: format!("t_{:x}", calculate_hash(&value)),
A quick check I think it could be empty, but this is only called from test or benches.

2023-09-15 19:22 UTC, kazimuth commented
I've integrated many of the changes here into #289. In particular, I tried iter_batched, then switched to a custom criterion timing loop so that we don't have to recreate the database every iteration. I don't have your `insert_batched` internal datastore changes though.

2023-09-26 18:47 UTC, mamcx commented
This PR have been made obsolete by https://github.com/clockworklabs/SpacetimeDB/pull/289

2023-09-26 18:48 UTC, mamcx commented
This is PR is obsoleted by https://github.com/clockworklabs/SpacetimeDB/pull/289

2023-09-26 18:48 UTC, closed without merging