Add spacetimedb_primitives::col_list::ColSet
clockworklabs/SpacetimeDB pull request #1691
Opened 2024-09-10 19:12 UTC by kazimuth

# Description of Changes

I want to use this for constraints in `ModuleDef`.

# API and ABI breaking changes

None

# Expected complexity level and risk

1, this adds unsafe code but it's fairly trivial.

# Testing

Added a proptest.

2024-09-10 20:07 UTC, Centril requested changes

2024-09-10 20:14 UTC, kazimuth commented on crates/primitives/src/col_list.rs
> +    // Don't implement `insert` because it'll be O(n^2) if we want to keep the set sorted on the heap.
Right, I was thinking of repeated insertion which is unclear from the comment.

2024-09-10 20:18 UTC, kazimuth commented on crates/primitives/src/col_list.rs
> +    /// Sort and deduplicate the list in place.
Yeah the "in place" was from when it wasn't deduplicating yet (proptests pointed out to me it needs to do that as well), so it's wrong. Will fix

2024-09-11 17:19 UTC, kazimuth commented
@Centril comments addressed :)

2024-09-11 17:32 UTC, Centril approved these changes

2024-09-11 19:38 UTC, merged