CLI - Remove `dns` subcommand
clockworklabs/SpacetimeDB pull request #1694
Opened 2024-09-10 19:54 UTC by bfops

# Description of Changes

The `dns` subcommand is half-finished. We are removing it for now.

If/when we decide to add it back in the future, we will make a separate proposal for it.

# API and ABI breaking changes

This removes the `spacetime dns` command.

# Expected complexity level and risk

1

# Testing

Existing CI only.

2024-11-23 00:44 UTC, cloutiertyler commented
I'm recommending we keep this as a P1 because if we don't then we need the docs to explain what `dns` is and all that and we don't want to bother with that because it's going to be confusing since it's not literally `dns` at this point.

2024-12-30 18:54 UTC, gefjon commented
Tyler says: we should have a `spacetime database rename` command (or `spacetime rename`? Like what we do for servers.) which renames a database. We should call these "database names," and not use the word "DNS."

2025-01-03 15:09 UTC, bfops commented on crates/cli/src/util.rs
> +    config: &Config,
unrelated cleanup. I think this function used to manage identities in some way, but no longer needs a `&mut Config` since our identity management is more global now.

2025-01-03 15:10 UTC, bfops commented on crates/cli/src/subcommands/dns.rs
> +    match spacetime_register_tld(&config, domain, server).await? {
note: this new `exec` function is a combination of the previous `exec_register_tld` and `exec_set_name` functions, now all-in-one.

2025-01-03 15:13 UTC, cloutiertyler commented
Could you add a test for this? Or point to the specific CI test that tests this command?

2025-01-03 15:15 UTC, bfops commented
> Could you add a test for this? Or point to the specific CI test that tests this command?

https://github.com/clockworklabs/SpacetimeDB/pull/1694/files#diff-c05a1f93f7bbe434d3be3d080b9aff1750af73d7e1fc2870a8a9c9c9550e89e9 has been updated

2025-01-07 02:51 UTC, cloutiertyler requested changes
See single comment.

2025-01-07 02:51 UTC, cloutiertyler commented on smoketests/tests/domains.py
> +        self.spacetime("logs", rand_name)
Not to be a stickler, but would it be possible to add the following tests:

- Test that you can't rename to a database that already exists
- Test that you can't publish a database with an invalid name (e.g. that includes special characters)

I would also keep the tests that test the slash functionality. We should only remove those tests when we actually change the server behavior. It's currently testing that behavior not this CLI comamnd.

2025-01-07 17:40 UTC, bfops commented on smoketests/tests/domains.py
> +        self.spacetime("logs", rand_name)
I've added the renaming test.

What special characters should be disallowed? I tried `!@#$%^&*()` and was able to publish successfully.

In a perfect world, I would argue that the "disallowed characters" test should be more internal, i.e. testing that the endpoints will return an error when using one of those symbols. Ideally I would say the CLI tests are relatively "thin" and test that the CLI does indeed correctly trigger the endpoints we expect it to.

2025-01-07 17:46 UTC, bfops commented on smoketests/tests/domains.py
> +        self.spacetime("logs", rand_name)
I've added back separate tests for the behavior of `/`

2025-01-07 18:31 UTC, cloutiertyler commented on smoketests/tests/domains.py
> +        self.spacetime("logs", rand_name)
Well these are not solely CLI tests but just generally smoke tests, although I do agree that should be a unit test/http test as well.

2025-01-07 21:05 UTC, cloutiertyler approved these changes
These changes now look good to me.

2025-01-07 21:41 UTC, merged