Subscriptions impl, server side
clockworklabs/SpacetimeDB pull request #1997
Opened 2024-11-15 17:01 UTC by lcodes

# Description of Changes

Moving subscriptions from one batch-subscribe call to one call per subscribe with matching unsubscribe call.

# API and ABI breaking changes

Updates to the websocket API and introduction of new messages.

# Expected complexity level and risk

3: changes the way subscriptions are stored and used.

# Testing

In progress

2024-11-19 18:04 UTC, Centril requested changes

2024-11-20 21:02 UTC, gefjon commented
@jsdt Note there's an edge case where republishing a module with a hot-swap can remove an index, which can break an indexed semijoin subscription query, since we refuse incremental semijoins which are not indexed on both of the joined columns. The intended semantics here is that, after a hotswap, we recompile all active subscribed queries. If any of them fails to compile, like in the removed-index case, the host sends an error message to the client and then ends the subscription, but the websocket connection is not closed. Any queries that successfully compile stay in place.

Please find out if this PR implements that behavior. If it does not, please create a ticket to fix it in a follow-up.

2024-11-21 17:11 UTC, jsdt commented on crates/client-api-messages/src/websocket.rs
> +    IdentityToken(IdentityToken),
What is the ids-not-names stuff?

2024-12-06 17:26 UTC, gefjon commented
Closing in favor of #2030

2024-12-06 17:26 UTC, closed without merging