perf(468): Add metric counters for committed transactions and rollbacks
clockworklabs/SpacetimeDB pull request #478
Opened 2023-10-26 16:33 UTC by joshua-spacetime

Closes #468.

# Description of Changes

# API and ABI

 - [ ] This is a breaking change to the module ABI
 - [ ] This is a breaking change to the module API
 - [ ] This is a breaking change to the ClientAPI
 - [ ] This is a breaking change to the SDK API

*If the API is breaking, please state below what will break*

# Expected complexity level and risk

*How complicated do you think these changes are? Grade on a scale from 1 to 5,
where 1 is a trivial change, and 5 is a deep-reaching and complex change.*

*This complexity rating applies not only to the complexity apparent in the diff,
but also to its interactions with existing and future code.*

*If you answered more than a 2, explain what is complex about the PR,
and what other components it interacts with in potentially concerning ways.*

2023-10-26 22:08 UTC, cloutiertyler approved these changes
I'll approve this, but I wonder if it would be a better design to put the `database_id` in the `Datastore` or the trait, and to put the transaction type and transaction info inside the Tx itself. Not sure if that's better tbh though, but food for thought.

Also why use the `database_id` rather than the database's `Address`? Please note that `database_id` should never be surfaced to SpacetimeDB users. It's purely internal. `Address` is the identifier for a database for users.

2023-10-26 22:12 UTC, cloutiertyler requested changes
Please replace `database_id` with `address` in the exposed metrics.

2023-10-27 16:51 UTC, kulakowski approved these changes
Just a note about naming.

2023-10-27 16:51 UTC, kulakowski commented on crates/core/src/db/datastore/traits.rs
> +    fn rollback_mut_tx_with_context(&self, ctx: &ExecutionContext, tx: Self::MutTxId);
Should this just stay `rollback_mut_tx`, and the test-only `rollback_mut_tx` get some worse name? Lots of things are going to plump around an ExecutionContext to the point that it doesn't seem exceptional or worth calling out.

2023-10-27 16:51 UTC, kulakowski commented on crates/core/src/db/datastore/traits.rs
> +    fn release_tx(&self, ctx: &ExecutionContext, tx: Self::TxId);
eg it is not `release_tx_with_context`

2023-10-27 17:13 UTC, kulakowski commented on crates/core/src/db/datastore/traits.rs
> +    fn rollback_mut_tx_with_context(&self, ctx: &ExecutionContext, tx: Self::MutTxId);
Yeah. Like I said, I'm happy to stamp another PR that changes em later if that's easier.

2023-10-28 02:26 UTC, cloutiertyler approved these changes
LGTM

2023-10-28 02:26 UTC, merged