This fixes replaying of the transaction log to no longer check constraints
clockworklabs/SpacetimeDB pull request #806
Opened 2024-02-08 07:42 UTC by cloutiertyler

# Description of Changes

Copied from Discord:

> Okay the reason that this wasn't a problem before was that we were not checking index constraints on replay before. This means that we were relying on the fact that the constraints would have been checked at or before commit time and that they have been baked into the message log.

> We actually **do not** want to check them at replay time because not only is it a pain, but actually **subtly wrong** the way we have it implemented. It's wrong because the actual constraints of the database may change as different transactions are added to the state and you would actually have to change your indexes and constraints as you replayed the log. This we are not currently doing (we're building all the non-bootstrapped indexes at the end after replaying), and thus aren't implementing constraint checking correctly as it stands.

> However, the above is all rendered moot anyway because we don't need to check constraints while replaying if we just assume that they were all checked prior to the transaction committing in the first place.

> Note also that operation/mutation ordering **does not** matter for operations inside a transaction of the message log assuming we only ever insert **OR** delete a unique row in one transaction. If we ever insert **AND** delete then order does matter. The issue above does not imply that order matters. Ordering of operations would **only** matter if you wanted to view the state of the database as of a partially applied transaction. We never actually want to do this, because after a transaction has been committed, it is assumed that all operations happen instantaneously and atomically at the timestamp of the transaction. The only time that we actually want to view the state of a database while a transaction is partially applied is while the transaction is running **before** it commits. Thus, we only care about operation ordering while the transaction is running, but we do not care about it at all in the context of the commit log.

> Not caring about the order in the log, however, requires that we do not check index constraints during replay of transaction operatoins. We could check them in between transactions if we wanted to update the indexes and constraints as they changed during replay, but that is unnecessary. 

> It seems that prior to mem-arch at least we **DO** delete and insert the same row within a transaction. This is always either a noop `(insert -> delete) or (insert) -> (delete -> insert)` or an insert `(doesn't exist) -> (delete -> insert)` depending on the order in the transaction and if it had been inserted before.

> Since this could differ the order does matter unless we avoid writing delete && insert in the same transaction. I am going to assume that the ordering in the message log currently **does mean something** for the old implemenation and that the new implementation does **NOT** ever insert an insert && delete into the message log.

# API and ABI breaking changes

None

# Expected complexity level and risk

4

2024-02-08 08:38 UTC, kim commented on crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
> +                        .insert_internal_allow_duplicate(blob_store, &row)
Is this indeed enough? This method doesn't update the pointer map, which seems important.

2024-02-08 08:38 UTC, kim commented on crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
> +        // after mem-arch.
```suggestion
        // the order of operations within a transaction does not matter
        // and that deleting and inserting the same row cannot occur in the commitlog.
```

It's not clear to me that or how this changed, namely the [TxState invariants](https://github.com/clockworklabs/SpacetimeDB/blob/master/crates/core/src/db/datastore/locking_tx_datastore/tx_state.rs#L36-L40). 

In any case, for a future reader it likely only matters that the order does not matter.

2024-02-08 14:25 UTC, gefjon requested changes
I can fix these easily, so I'll open a PR based on this with an added commit.

2024-02-08 20:53 UTC, gefjon approved these changes

2024-02-09 07:34 UTC, kim approved these changes

2024-02-12 22:05 UTC, merged